### PR TITLE
Made all line endings be \n in .csv

### PR DESCRIPTION
**Pull request by hildjj**
Changed the line endings of lines 94 and 96.

### CODE REVIEW

**Comment by hildjj** [comment]
Fixes #2.

**Comment by cabo** [comment]
The tests should stay as they are (with a CR embedded in some quoted text).
(The notation is not beautiful, this was just a quick way to add this test; we probably want a better way to do this.)

**Comment by hildjj** [comment]
Discussion in #2.
*strong* disagreement.

**Comment by hildjj** [comment]
Understood the intent, and understand that this isn't the way to solve the problem.

**Pull request closed without merging**
