### PR TITLE
Add numeric tests.

### PR DESCRIPTION
**Pull request by hildjj**
There are a bunch more tests coming.  Thought I would push them in chunks to see if we're on the same page before doing more.

### CODE REVIEW

**Comment by cabo** [comment]
Thanks.  Since my code doesn't do encoding indicators for numbers yes, I wouldn't mind splitting this up into more than a single basic.csv -- e.g., adding an encoding-indicators.csv

**Comment by hildjj** [comment]
I can do that.

**Comment by hildjj** [comment]
Btw, can you add instructions for how I can run your tests for someone who is Ruby illiterate?  I figured out how to get the dependencies installed (I think?) but I still have the error "cannot load such file -- cbor-diagnostic (LoadError)" when I run `rake t`.

**Comment by cabo** [comment]
Oh, gemspec had a missing dependency.  I also added the script "gebuin" (gem build & install).
So a `rake i t` should do it...
Thanks!

**Comment by cabo** [comment]
Now that I can test them, I added a few test cases to encoding-indicators.csv (on main, sorry).

I'm wondering whether we should do something to get a rounding equivalent of 1.1_2 -- this is currently rejected as an error because there is no way to represent the exact 64-bit binary64 for 1.1 in 2**2 bytes (single precision binary32).
Of course, that can be added (registered) later as 1.1_r2 or some such.
We haven't talked about rounding much, yet...

**Comment by hildjj** [comment]
Great tests, I found two more issues.  

I don't see the value in the rounding for the complexity.  But take it to the list, someone else may like it.

**Pull request merged**
